### ISSUE TITLE
3D positional encoding

### ISSUE THREAD

**Issue by tmquan** [wzlxjtu/PositionalEncoding2D#3]
The layout of 2d is interleaving in the matrix. 
However, I would like to ask whether 3D is applicable?

Thanks,

**Comment by wzlxjtu** [comment]
Hi @tmquan, I haven't tried but I think it should work. It could be easily extended to 3D by simply splitting the feature space into three parts, each representing one dimension.

**Comment by tatp22** [comment]
Hey,

I made a 3d implementation here, you can go and check it out: https://github.com/tatp22/multidim-positional-encoding

**Comment by tmquan** [comment]
> Hey,
> 
> I made a 3d implementation here, you can go and check it out: https://github.com/tatp22/multidim-positional-encoding
> 
> It's based on this repo, and the formulas follow similarly

Nice, thanks. 
It would be better to have 'channel first' instead of 'channel last' to promote its usability to other PyTorch users. 
Other than that, everything is in place.
